development:
  adapter: postgresql
  database: sinatra_development
  username: postgres
  password: 
  host: localhost

production:
  adapter: postgresql
  database: sinatra_development
  username: plreqjinrpdmqz
  password: RC97USfJEZx6gGBUIISzcL64En
  host: ec2-174-129-21-42.compute-1.amazonaws.com
  port: 5432